version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:${ELK_VERSION:-8.14.0}
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  logstash:
    image: logstash:${ELK_VERSION:-8.14.0}
    container_name: logstash
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
    environment:
      - cluster.name=es-cluster
    networks:
      - elastic

  kibana:
    image: kibana:${ELK_VERSION:-8.14.0}
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
