version: '3.8'

services:

  kafka:
    image: apache/kafka:${KAFKA_VERSION:-3.7.0}
    container_name: kafka
    ports:
      - 9092:9092
      - 2181:2181
    volumes:
      - kafka_data:/tmp
    networks:
      - kafka_network
    # start with zookeeper
#    command: bash -c 'nohup ./opt/kafka/bin/zookeeper-server-start.sh ./opt/kafka/config/zookeeper.properties'

volumes:
  kafka_data:

networks:
  kafka_network:
    driver: bridge
