version: '3.8'

services:

  redis-master:
    image: redis:${REDIS_VERSION:-alpine}
    hostname: redis
    container_name: redis-master
    ports:
      - 6379:6379
    networks:
      - redis
    command: ["redis-server", "--appendonly", "yes"]

  redis-slave:
    image: redis:${REDIS_VERSION:-alpine}
    container_name: redis-slave
    ports:
      - 6380:6379
    depends_on:
      - redis-master
    networks:
      - redis
    command: ["redis-server", "--slaveof", "redis-master", "6379"]

networks:
  redis: